web_books/web_books/urls.py
from django.contrib import admin
from django.urls import path, include
from catalog import views

urlpatterns = [
    # Админка и Аккаунты

    path('admin/', admin.site.urls),
    path('accounts/login/', views.LoginUser.as_view(), name="login"),  # Маршрут для входа (Переназначение)
    path('accounts/', include("django.contrib.auth.urls")),  # Маршрут для работы с аккаунтами
    path('accounts/registration', views.registration, name="registration"),  # Маршрут для регистрации

    # Статические маршруты
    path('', views.index, name="index"),  # Главная страница
    path('books/', views.BookListView.as_view(), name="books"),  # Все книги (/books/?page=2)
    path('authors/', views.AuthorListView.as_view(), name="authors"),  # Все авторы
    # Страница. Список всех экземпляров прикрепленных к пользователю

    # Динамические маршруты (название переменной обязательно: "pk")
    path('book/<int:pk>', views.BookDetailView.as_view(), name="book"),  # Конкретная книга

    # Страницы касательно [Редактирования авторов] 4шт.
    # Страницы касательно [Редактирования книг] 3шт.

]

web_books/catalog/models.py
from django.db import models
from django.contrib.auth.models import User  # импортируем встроенную модель "Пользователи"


# 1. Модель Жанры (Genre)
# Поля: name(жанр)
class Genre(models.Model):
    name = models.CharField(max_length=200,
                            help_text="Введите жанр книги",
                            verbose_name="Жанр Книги")

    # При просмотре всей модели из админки (поле которое будет отображаться)
    def __str__(self):
        return self.name

    # НАСТРОЙКИ перевода модели и сортировки объектов на главной таблице
    class Meta:
        verbose_name = "Жанр"  # Название модели в ед. Числе
        verbose_name_plural = "Жанры"  # Название модели во мн. Числе
        ordering = ["name"]  # Сортировка по полю


# 2. Модель Авторы (Author)
# Поля: first_name(Имя автора), last_name(Фамилия), date_of_birth(дата рождения), date_of_death(дата смерти)
class Author(models.Model):
    first_name = models.CharField(max_length=100, help_text="Введите имя автора", verbose_name="Имя автора")
    last_name = models.CharField(max_length=100, help_text="Введите фамилию автора", verbose_name="Фамилия автора")
    date_of_birth = models.DateField(null=True, blank=True, help_text="Введите дату рождения",
                                     verbose_name="дата рождения")
    date_of_death = models.DateField(null=True, blank=True, help_text="Введите дату смерти", verbose_name="дата смерти")

    # При просмотре всей модели из админки (поле которое будет отображаться)
    def __str__(self):
        return "{} {}".format(self.first_name, self.last_name)

    # НАСТРОЙКИ перевода модели и сортировки объектов на главной таблице
    class Meta:
        verbose_name = "Автора"  # Название модели в ед. числе род. падежа
        verbose_name_plural = "Авторы"  # Название модели во мн. числе
        ordering = ["last_name"]  # Сортировка по полю (если со знаком "-" то в обратном порядке)


# 3. Модель Язык (Language)
# Поля: name(Язык)
class Language(models.Model):
    name = models.CharField(max_length=20, help_text="Введите язык книги", verbose_name="Язык книги")

    # При просмотре всей модели из админки (поле которое будет отображаться)
    def __str__(self):
        return self.name

    # НАСТРОЙКИ перевода модели и сортировки объектов на главной таблице
    class Meta:
        verbose_name = "Язык"  # Название модели в ед. числе род. падежа
        verbose_name_plural = "Языки"  # Название модели во мн. числе
        ordering = ["name"]  # Сортировка по полю


# 4. Модель Книг (Books)
# Поля (со связями): author(Автор-ManyToManyField), genre(Жанр-ForeignKey), language(Язык-ForeignKey),
# Поля (обычные): title(Название), summary(Описание), isbn(Код книги)
class Book(models.Model):
    objects = None
    author = models.ManyToManyField(Author, help_text="Выберите автора книги", verbose_name="Автор книги")
    genre = models.ForeignKey(Genre, null=True, on_delete=models.CASCADE, help_text="Выберите жанр книги", verbose_name="Жанр книги")
    language = models.ForeignKey(Language, null=True, on_delete=models.CASCADE, help_text="Выберите язык книги", verbose_name="Язык книги")
    title = models.CharField(max_length=200, help_text="Введите название книги", verbose_name="Название книги")
    summary = models.TextField(max_length=1000, help_text="Введите описание книги", verbose_name="Описание книги")
    isbn = models.CharField(max_length=200, help_text="Должно содержать 13 символов", verbose_name="ISBN книги")

    # [ВНУТРЕННИЙ МЕТОД]. Получить все фамилии авторов книг (Метод показа [всех авторов]). НУЖЕН ЕСЛИ СВЯЗЬ ManyToManyField !!
    def get_authors(self):
        # 1 способ
        # lst_authors = [a.last_name for a in self.author.all()]
        # str_authors = str(lst_authors)

        # 2 способ
        lst_authors = []
        for author in self.author.all():
            lst_authors.append(author.last_name)
        return ", ".join(lst_authors)

    # [ВНУТРЕННИЙ МЕТОД]. Метод возвращающий ссылку на книгу
    def get_absolute_url(self):
        return "/book/{}".format(self.pk)  # self.pk тоже самое что self.id

    # Подписать столбик (что бы при выводе названии, колонка была не как название функции, а как укажем)
    get_authors.short_description = "Авторы"

    # При просмотре всей модели из админки (поле которое будет отображаться)
    def __str__(self):
        return self.title

    # НАСТРОЙКИ перевода модели и сортировки объектов на главной таблице
    class Meta:
        verbose_name = "Книгу"  # Название модели в ед. числе род. падежа
        verbose_name_plural = "Книги"  # Название модели во мн. числе
        ordering = ["title"]  # Сортировка по полю


# 5. Модель Состояние (Status)
# Поля: name(Состояние)
class Status(models.Model):
    name = models.CharField(max_length=20, help_text="Введите статус экземпляра книги",
                            verbose_name="Статус экземпляра книги")

    # При просмотре всей модели из админки (поле которое будет отображаться)
    def __str__(self):
        return self.name

    # НАСТРОЙКИ перевода модели и сортировки объектов на главной таблице
    class Meta:
        verbose_name = "Статус"  # Название модели в ед. числе род. падежа
        verbose_name_plural = "Статусы"  # Название модели во мн. числе
        ordering = ["name"]  # Сортировка по полю


# 6. Модель Экземпляр (BookInstance)
# Поля (связи): book(Книга-OneToManyField), status(Статус-ForeignKey), borrower(Заказчик - ForeignKey)
# Поля (обычные): due_back(Дата возврата), imprint(Издательство), inv_nom(Инвентарный номер)
class BookInstance(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE, null=True, help_text="Введите название книги", verbose_name="Название книги")
    inv_nom = models.CharField(max_length=20, null=True, help_text="Введите инвентарный номер экземпляра",
                               verbose_name="Инвентарный номер")
    imprint = models.CharField(max_length=200, help_text="Введите издательство и год выпуска",
                               verbose_name="Издательство")
    status = models.ForeignKey(Status, on_delete=models.CASCADE, null=True, help_text='Изменить состояние экземпляра',
                               verbose_name="Статус экземпляра книги")
    due_back = models.DateField(null=True, blank=True, help_text="Введите конец срока статуса",
                                verbose_name="Дата окончания статуса")
    borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, help_text="Заказчик", verbose_name="Выберите заказчика книги")

    # [ВНУТРЕННИЙ МЕТОД]. Проверка не просрочен ли срок возврата книги.
    pass

    # При просмотре всей модели из админки (поле которое будет отображаться)
    def __str__(self):
        return '№{}, {}, ({})'.format(self.inv_nom, self.book, self.status)

    # НАСТРОЙКИ перевода модели и сортировки объектов на главной таблице
    class Meta:
        verbose_name = "Экземпляр"  # Название модели в ед. числе род. падежа
        verbose_name_plural = "Экземпляры"  # Название модели во мн. числе
        ordering = ["inv_nom"]  # Сортировка по полю

web_books/catalog/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm


# Создание формы Регистрации
class Registration(forms.Form):
    username = forms.CharField(label="Логин", max_length=10, widget=forms.widgets.TextInput(
        attrs={'class': 'form-control', 'id': "floatingInput", "placeholder": "username"}))
    password = forms.CharField(label="Пароль", widget=forms.widgets.PasswordInput(
        attrs={'class': 'form-control', 'id': "floatingInput", "placeholder": "username"}))
    email = forms.EmailField(label="Email", required=False, help_text="(не обязательно)",
                             widget=forms.widgets.EmailInput(
                                 attrs={'class': 'form-control', 'id': "floatingInput", "placeholder": "username"}))


# Переназначение (На основе наследования) формы Входа
class Login(AuthenticationForm):
    username = forms.CharField(label="Логин", max_length=10, widget=forms.widgets.TextInput(
        attrs={'class': 'form-control', 'id': "floatingInput", "placeholder": "username"}))
    password = forms.CharField(label="Пароль", widget=forms.widgets.PasswordInput(
        attrs={'class': 'form-control', 'id': "floatingInput", "placeholder": "username"}))

web_books/catalog/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import *  # Импорт всех моделей
from .forms import *
from django.views import generic  # Нужен для автоматического чтения
from django.contrib.auth.views import LoginView
from django.db.utils import IntegrityError


# Create your views here.


# Главная страница
def index(request):
    # Получаем необходимые данные
    num_books = len(Book.objects.all())  # Количество книг
    num_instances = len(BookInstance.objects.all())  # Количество экземпляров
    num_instances_available = len(BookInstance.objects.filter(status__name="на складе"))
    num_authors = len(Author.objects.all())  # Количество авторов

    # Пример работы с сессиями (подсчитывает кол-во посещений этой страницы)
    # Количество визитов (Получить значение сессии, если не существует - то "0")
    num_visits = request.session.get("num_visits", 0)
    request.session['num_visits'] = int(num_visits) + 1  # Запись нового значения (кол-ва визитов) в сессию

    # Передаем в шаблон
    context = {"num_books": num_books,
               "num_instances": num_instances,
               "num_instances_available": num_instances_available,
               "num_authors": num_authors,
               "num_visits": num_visits}

    return render(request, 'index.html', context=context)


# Страница регистрации аккаунта
def registration(request):
    if request.method == "GET":
        # Создание формы:
        form = Registration()
        # Генерация данных (context)
        context = {"form": form}
        # Показываем шаблон
        return render(request, "registration/registration.html", context=context)

    if request.method == "POST":
        # Получаем данные из формы
        username = request.POST.get("username")
        password = request.POST.get("password")
        email = request.POST.get("email", "")
        try:
            # Записываем данные в БД (нового пользователя)
            User.objects.create_user(username, password, email).save()
            # Генерация данных (context)
            context = {"username": username}
            # Показываем шаблон
            return render(request, "registration/registration.html", context=context)
        except IntegrityError:
            # Генерация данных (context)
            context = {"error": username}
            # Показываем шаблон
            return render(request, "registration/registration.html", context=context)


# Страница входа в аккаунт (Переназначение)
class LoginUser(LoginView):
    form_class = Login
    template_name = "registration/login.html"


# Возвращает список всех книг. (Автоматически генерируется при помощи ListView)
# Шаблон "templates/catalog/book_list.html"
# Переменная (шаблона/ключ): "book_list"
class BookListView(generic.ListView):
    model = Book
    paginate_by = 2  # Сколько обьектов будет передано в шаблон


# Возвращает конкретную книгу. (Автоматически генерируется при помощи DetailView)
# Шаблон "templates/catalog/book_detail.html"
# Переменная (входная): "int:pk"
# Переменная (шаблона/ключ): "book"
class BookDetailView(generic.DetailView):
    model = Book


# Возвращает всех Авторов. (Автоматически генерируется при помощи ListlView)
# Шаблон "templates/catalog/author_list.html"
# Переменная (входная): ""
# Переменная (шаблона/ключ): "author_list"
class AuthorListView(generic.ListView):
    model = Author
    paginate_by = 3  # Сколько обьектов будет передано в шаблон

web_books/templates/catalog/author_list.html
{% extends "base.html" %}

<!-- Блок Заголовка -->
{% block title %}Мир книг (авторы){% endblock %}

<!-- Блок Контента -->
{% block content %}
<h1>Список авторов в БД</h1>
{% if author_list %}
    <table class="table">
        <tbody>
        {% for author in author_list %}
            <tr><th scope="row">{{ author.first_name }} {{ author.last_name }}</th><td>{{ author.date_of_birth }}</td><td>{{ author.date_of_death }}</td></tr>
        {% endfor %}
        </tbody>
    </table>
    <!-- Кнопки перехода между страницами -->
    <!-- request.path - текущий URl страницы -->
    <!-- page_obj.has_previous/has_next - Есть ли страница (True) -->
    <!-- page_obj.previous_page_number/next_page_number - Возвращают цифру предыдущей или следующей страницы соответственно -->
    <div class="btn-group" role="group" aria-label="Second group">
        {% if page_obj.has_previous %}
        <a class="btn btn-sm btn-outline-secondary" href="{{ request.path }}?page={{ page_obj.previous_page_number }}">Предыдущая</a>
        {% endif %}
        <a class="btn btn-sm btn-outline-secondary" href="#">{{ page_obj.number }} из {{ page_obj.paginator.num_pages }}</a>
        {% if page_obj.has_next %}
        <a class="btn btn-sm btn-outline-secondary" href="{{ request.path }}?page={{ page_obj.next_page_number }}">Следующая</a>
        {% endif %}
    </div>
    <!-- Конец. Кнопки перехода между страницами -->
{% else %}
    <p>В базе данных нет авторов!</p>
{% endif %}
{% endblock %}

web_books/templates/catalog/book_detail.html
{% extends "base.html" %}

<!-- БЛОК Контент -->
{% block title %} Мир книг ({{ book.title }}){% endblock %}

{% block content %}
  <h2>Название книги: {{ book.title }}</h2>
  <p><b>Жанр:</b> {{ book.genre }}</p>
  <p><b>Аннотация:</b> {{ book.summary }}</p>
  <p><b>ISBN:</b> {{ book.isbn }}</p>
  <p><b>Язык:</b> {{ book.language }}</p>
  <p><b>Автор(ы):</b><a href="">{{ book.get_authors }}</a> </p>

  <h4>Количество экземпляров книг в БД:</h4>
  <ul>
  {% for instance in book.bookinstance_set.all %}
    <li><span class=" {% if instance.status.name == 'на складе' %} text-success
                      {% elif instance.status.name == 'в заказе' %} text-warning
                      {% else %} text-danger
                      {% endif %}">{{ instance }}</span></li>
    <p><b>Издательство:</b>{{ instance.imprint }}</p>
    <p class="text-muted"><b>Инвентарный номер: </b>{{ instance.inv_nom }}</p>
    <p><b>Статус экземпляра книги в БД: </b>{{ instance.status.name }}</p><br><hr>
  {% endfor %}
  </ul>
{% endblock %}

web_books/templates/catalog/book_list.html
{% extends "base.html" %}

<!-- БЛОК Контент -->
{% block title %}Мир книг (книги){% endblock %}

{% block content %}
    <h1>Список книг в БД</h1>
    {% if book_list %}
        <ul>
            {% for book in book_list %}
            <li>
                <a href="{{ book.get_absolute_url }}">{{ book.title }}</a> ({{ book.genre }})
            </li>
            {% endfor %}
        </ul>
        <!-- Кнопки перехода между страницами -->
    <!-- request.path - текущий URl страницы -->
    <!-- page_obj.has_previous/has_next - Есть ли страница (True) -->
    <!-- page_obj.previous_page_number/next_page_number - Возвращают цифру предыдущей или следующей страницы соответственно -->
    <div class="btn-group" role="group" aria-label="Second group">
        {% if page_obj.has_previous %}
        <a class="btn btn-sm btn-outline-secondary" href="{{ request.path }}?page={{ page_obj.previous_page_number }}">Предыдущая</a>
        {% endif %}
        <a class="btn btn-sm btn-outline-secondary" href="#">{{ page_obj.number }} из {{ page_obj.paginator.num_pages }}</a>
        {% if page_obj.has_next %}
        <a class="btn btn-sm btn-outline-secondary" href="{{ request.path }}?page={{ page_obj.next_page_number }}">Следующая</a>
        {% endif %}

    <!-- Конец кнопок перехода между страницами -->
    {% else %}
            <p>В базе данных нет книг!</p>
    {% endif %}
{% endblock %}